# Generated by Django 4.2.6 on 2023-10-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
