# Generated by Django 4.2.6 on 2023-10-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_bio_alter_user_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
