# Generated by Django 4.2.6 on 2025-02-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
